# Generated by Django 6.0 on 2026-01-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_merge_migrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='seat_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
